[project]
name = "pokefetch"
version = "0.1.0"
description = "FastAPI project to fetch Pokemon"
authors = [
    { name = "Benjamin Davies", email = "benjamin@the-davies.net" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.143.0",
    "psycopg[binary]>=3.3.6",
    "sqlalchemy>=2.1.4",
]

[project.scripts]
pokefetch = "pokefetch:main"

[build-system]
requires = ["uv_build>=0.13.0,<0.14.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx2>=2.13.1",
    "pytest>=9.1.1",
    "ruff>=0.17.0",
]

[tool.fastapi]
entrypoint = "pokefetch.main:app"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
